# Generated by Django 3.0.2 on 2020-03-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backgroundimage',
        ),
    ]
