# Generated by Django 3.0.2 on 2020-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
